# -*- coding: utf-8 -*-
"""Project(digits classification dataset).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IQP-3kjCPJvFEPAjNJnYg4w6MPrICETm
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Importing the libraries"""

import tensorflow as tf
from tensorflow import keras#its used to import the inbuilt Data set

"""Deeplearning Libraries

Importing the Dataset
"""

data=keras.datasets.mnist

data

df=data.load_data()

(x_train,y_train),(x_test,y_test)=df

x_train.shape

y_train.shape

x_test.shape

x_train[0]#to see a single image in the form of pixel

plt.matshow(x_train[0])#all the dark areas represent the zeroes and the restare of different values in the matrices

for i in range(10):
  plt.matshow(x_train[i])

y_test.shape

y_test.ndim #to know the dimension

y_train.ndim

x_test.ndim

x_train.ndim

x_train_flat=x_train.reshape(len(x_train),28*28)
x_test_flat=x_test.reshape(len(x_test),28*28)

x_train_flat[0].ndim

"""ANN Model creation"""

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model=Sequential([
                  Dense(units=10,
                        input_shape=(784,),
                        activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss ='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

"""Training/Fit the model"""

model.fit(x_train_flat,y_train,epochs=10)

y_pred = model.predict(x_test_flat)

y_pred

model.evaluate(x_test_flat,y_test)

